runtime: python311
entrypoint: gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 app:app

env_variables:
  FLASK_ENV: "production"
  PYTHONUNBUFFERED: "1"

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.75